connection:
  mysql:
    enable: false
    address: "localhost:3306"
    username: "root"
    password: ""
    database: "test"
  sqlite:
    file: "online-time.sql"

# De quanto em quantos minutos irá atualizar o tempo dos jogadores
# Recomendado: 10 minutos
updaterTime: 10

# Formatos: MINUTES ou HOURS
# Recomendado: MINUTES
timeFormat: MINUTES